version: v{build}

platform: 
  - x86
  - x64

environment:
  global:
    CHERE_INVOKING: 1
    MSYS2_PATH: c:\msys64

  matrix:

  - job_name: MSYS2
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: VS
    appveyor_build_worker_image: Visual Studio 2017

matrix:
  fast_finish: true

init:
  - appveyor version

# job-specific configurations
for:

  -
    matrix:
      only:
        - job_name: MSYS2

    build_script:
    - cmd: echo This is MSYS2-specific build script for %PLATFORM%

  -
    matrix:
      only:
        - job_name: VS

    build_script:
    - |-
      echo This is Visual Studio-specific build script %PLATFORM%
      echo test






