version: v{build}

platform: 
  - x86
  - x64

environment:
  global:
    CHERE_INVOKING: 1
    MSYS2_PATH: c:\msys64
    TOKEN:
      secure: oNuYjlZq1+hGSdIYUexbVwsRVjpquP56ngjPL4u+9zY=

  matrix:
  - job_name: BAKE
    appveyor_build_worker_image: Visual Studio 2019

  - job_depends_on: BAKE
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: VS
    BUILDER: MSYS2
    appveyor_build_worker_image: Visual Studio 2017

matrix:
  fast_finish: true
  exclude:
    - job_name: BAKE
      platform: x64

init:
  - appveyor version

# job-specific configurations
for:
  -
    matrix:
      only:
        - job_name: BAKE
        - configuration : x86

    build_script:
    - |-
      echo BAKING for others
      echo %TIME% > baked.txt
      appveyor PushArtifact baked.txt

  -
    matrix:
      only:
        - BUILDER: MSYS2

    build_script:
    - |-
      set MSYSTEM=%PLATFORM:86=32%
      set MSYSTEM=%MSYSTEM:x=MINGW%
      echo This is MSYS2-specific build script for %PLATFORM% : %MSYSTEM%
      curl -o projects.json -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" https://ci.appveyor.com/api/projects/oxillo/appveyor-experiments
      bash -c "sed -e 's/{/\n{/g' -e 's/}/}\n/g' projects.json | grep \"jobId\" > jobsid.txt"
      bash -c "grep \"BAKE\" jobsid.txt | sed -e 's/.*jobId\":\"//' -e 's/\",.*//' > bake.id"
      set /p BAKE_ID=<bake.id
      set job_name=MSYS2_%MSYSTEM%
      appveyor DownloadFile %APPVEYOR_URL%/api/buildjobs/%BAKE_ID%/artifacts/baked.txt
      cat baked.txt
      
      

  -
    matrix:
      only:
        - job_name: VS_{platform}

    build_script:
    - |-
      set BITS=%PLATFORM:86=32%
      set BITS=%BITS:x=%
      echo This is Visual Studio-specific build script %PLATFORM% : %BITS%
      echo test






