version: v{build}

platform: 
  - x86
  - x64

environment:
  global:
    CHERE_INVOKING: 1
    MSYS2_PATH: c:\msys64

  matrix:
  - job_name: BAKE
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: MSYS2
    job_depends_on: BAKE
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: VS
    appveyor_build_worker_image: Visual Studio 2017

matrix:
  fast_finish: true
  exclude:
    - job_name: BAKE
      platform: x64
      
cache:
  - jobcache

init:
  - appveyor version

# job-specific configurations
for:
  -
    matrix:
      only:
        - job_name: BAKE
        - configuration : x86

    build_script:
    - |-
      echo BAKING for others
      set
      mkdir %APPVEYOR_BUILD_FOLDER%\jobcache
      echo %TIME% > %APPVEYOR_BUILD_FOLDER%\jobcache\baked.txt
      echo %TIME% > baked.txt
      appveyor PushArtifact baked.txt
      echo %TIME% > %APPVEYOR_BUILD_FOLDER%\jobcache\baked.txt

  -
    matrix:
      only:
        - job_name: MSYS2

    build_script:
    - |-
      appveyor DownloadFile %APPVEYOR_URL%/api/projects/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_NAME%/artifacts/baked.txt?job=BAKE
      set
      cat baked.txt
      set MSYSTEM=%PLATFORM:86=32%
      set MSYSTEM=%MSYSTEM:x=MINGW%
      echo This is MSYS2-specific build script for %PLATFORM% : %MSYSTEM%
      cat %APPVEYOR_BUILD_FOLDER%\jobcache\baked.txt

  -
    matrix:
      only:
        - job_name: VS

    build_script:
    - |-
      set BITS=%PLATFORM:86=32%
      set BITS=%BITS:x=%
      echo This is Visual Studio-specific build script %PLATFORM% : %BITS%
      echo test






